
package br.gov.ans.tiss.ws.tipos.tisssolicitacaoprocedimento.v30500;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import br.gov.ans.padroes.tiss.schemas.v30500.AutorizacaoProcedimentoWS;
import br.gov.ans.padroes.tiss.schemas.v30500.SolicitacaoProcedimentoWS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tissSolicitacaoProcedimento_PortType", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30500")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.gov.ans.padroes.tiss.schemas.v30500.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface TissSolicitacaoProcedimentoPortType {


    /**
     * 
     * @param solicitacaoProcedimento
     * @return
     *     returns br.gov.ans.padroes.tiss.schemas.v30500.AutorizacaoProcedimentoWS
     * @throws TissFault
     */
    @WebMethod(operationName = "tissSolicitacaoProcedimento_Operation")
    @WebResult(name = "autorizacaoProcedimentoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "autorizacaoProcedimento")
    public AutorizacaoProcedimentoWS tissSolicitacaoProcedimentoOperation(
        @WebParam(name = "solicitacaoProcedimentoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "prestadorParaOperadora")
        SolicitacaoProcedimentoWS solicitacaoProcedimento)
        throws TissFault
    ;

}
