
package br.gov.ans.tiss.ws.tipos.tisssolicitacaoprocedimento.v30500;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tissSolicitacaoProcedimento", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30500", wsdlLocation = "http://url_webservice/TISS30500OPS/tissSolicitacaoProcedimento?wsdl")
public class TissSolicitacaoProcedimento
    extends Service
{

    private final static URL TISSSOLICITACAOPROCEDIMENTO_WSDL_LOCATION;
    private final static WebServiceException TISSSOLICITACAOPROCEDIMENTO_EXCEPTION;
    private final static QName TISSSOLICITACAOPROCEDIMENTO_QNAME = new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30500", "tissSolicitacaoProcedimento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://url_webservice/TISS30500OPS/tissSolicitacaoProcedimento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TISSSOLICITACAOPROCEDIMENTO_WSDL_LOCATION = url;
        TISSSOLICITACAOPROCEDIMENTO_EXCEPTION = e;
    }

    public TissSolicitacaoProcedimento() {
        super(__getWsdlLocation(), TISSSOLICITACAOPROCEDIMENTO_QNAME);
    }

    public TissSolicitacaoProcedimento(WebServiceFeature... features) {
        super(__getWsdlLocation(), TISSSOLICITACAOPROCEDIMENTO_QNAME, features);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation) {
        super(wsdlLocation, TISSSOLICITACAOPROCEDIMENTO_QNAME);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TISSSOLICITACAOPROCEDIMENTO_QNAME, features);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TissSolicitacaoProcedimentoPortType
     */
    @WebEndpoint(name = "tissSolicitacaoProcedimento_Port")
    public TissSolicitacaoProcedimentoPortType getTissSolicitacaoProcedimentoPort() {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30500", "tissSolicitacaoProcedimento_Port"), TissSolicitacaoProcedimentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TissSolicitacaoProcedimentoPortType
     */
    @WebEndpoint(name = "tissSolicitacaoProcedimento_Port")
    public TissSolicitacaoProcedimentoPortType getTissSolicitacaoProcedimentoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30500", "tissSolicitacaoProcedimento_Port"), TissSolicitacaoProcedimentoPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TISSSOLICITACAOPROCEDIMENTO_EXCEPTION!= null) {
            throw TISSSOLICITACAOPROCEDIMENTO_EXCEPTION;
        }
        return TISSSOLICITACAOPROCEDIMENTO_WSDL_LOCATION;
    }

}
