
package br.gov.ans.tiss.ws.tipos.tisssolicitacaoprocedimento.v30500;

import javax.xml.ws.WebFault;
import br.gov.ans.padroes.tiss.schemas.TissFaultWS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "tissFaultWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas")
public class TissFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TissFaultWS faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TissFault(String message, TissFaultWS faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TissFault(String message, TissFaultWS faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.gov.ans.padroes.tiss.schemas.TissFaultWS
     */
    public TissFaultWS getFaultInfo() {
        return faultInfo;
    }

}
