
package br.gov.ans.tiss.ws.tipos.tisssolicitacaoprocedimento.v30301;

import br.gov.ans.padroes.tiss.schemas.v30301.AutorizacaoProcedimentoWS;
import br.gov.ans.padroes.tiss.schemas.v30301.ObjectFactory;
import br.gov.ans.padroes.tiss.schemas.v30301.SolicitacaoProcedimentoWS;
import config.WsConfiguration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tissSolicitacaoProcedimento_PortType", targetNamespace = WsConfiguration.TARGET_NAMESPACE_URL +  "tisssolicitacaoprocedimento/v30301")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class,
    org.w3._2000._09.xmldsig_.v30301.ObjectFactory.class
})
public interface TissSolicitacaoProcedimentoPortType {


    /**
     * 
     * @param solicitacaoProcedimento
     * @return
     *     returns br.gov.ans.padroes.tiss.schemas.AutorizacaoProcedimentoWS
     * @throws TissFault
     */
    @WebMethod(operationName = "tissSolicitacaoProcedimento_Operation")
    @WebResult(name = "autorizacaoProcedimentoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "autorizacaoProcedimento")
    public AutorizacaoProcedimentoWS tissSolicitacaoProcedimentoOperation(
        @WebParam(name = "solicitacaoProcedimentoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "solicitacaoProcedimento")
                SolicitacaoProcedimentoWS solicitacaoProcedimento)
        throws TissFault
    ;

}
