package com.spin.verificaelegibilidade.tiss.br.gov.ans;

public enum TipoTransacaoTiss {

    ENVIO_LOTE_GUIAS,
    ENVIO_ANEXO,
    SOLIC_DEMONSTRATIVO_RETORNO,
    SOLIC_STATUS_PROTOCOLO,
    SOLICITACAO_PROCEDIMENTOS,
    SOLICITA_STATUS_AUTORIZACAO,
    VERIFICA_ELEGIBILIDADE,
    CANCELA_GUIA,
    COMUNICACAO_BENEFICIARIO,
    RECURSO_GLOSA,
    SOLIC_STATUS_RECURSO_GLOSA,
    PROTOCOLO_RECEBIMENTO,
    PROTOCOLO_RECEBIMENTO_ANEXO,
    RECEBIMENTO_RECURSO_GLOSA,
    DEMONSTRATIVO_ANALISE_CONTA,
    DEMONSTRATIVO_PAGAMENTO,
    DEMONSTRATIVO_ODONTOLOGIA,
    SITUACAO_PROTOCOLO,
    RESPOSTA_SOLICITACAO,
    AUTORIZACAO_ODONTOLOGIA,
    STATUS_AUTORIZACAO,
    SITUACAO_ELEGIBILIDADE,
    CANCELAMENTO_GUIA_RECIBO,
    RECIBO_COMUNICACAO,
    RESPOSTA_RECURSO_GLOSA;

    public static TipoTransacaoTiss fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
