
package br.gov.ans.tiss.ws.tipos.v30301.tissverificaelegibilidade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tissVerificaElegibilidade", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tissverificaelegibilidade/v30301", wsdlLocation = "http://webservicehml.unimedblumenau.com.br:8082/TISS30301OPS/tissVerificaElegibilidade?wsdl")
public class TissVerificaElegibilidade
    extends Service
{

    private final static URL TISSVERIFICAELEGIBILIDADE_WSDL_LOCATION;
    private final static WebServiceException TISSVERIFICAELEGIBILIDADE_EXCEPTION;
    private final static QName TISSVERIFICAELEGIBILIDADE_QNAME = new QName("http://www.ans.gov.br/tiss/ws/tipos/tissverificaelegibilidade/v30301", "tissVerificaElegibilidade");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservicehml.unimedblumenau.com.br:8082/TISS30301OPS/tissVerificaElegibilidade?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TISSVERIFICAELEGIBILIDADE_WSDL_LOCATION = url;
        TISSVERIFICAELEGIBILIDADE_EXCEPTION = e;
    }

    public TissVerificaElegibilidade() {
        super(__getWsdlLocation(), TISSVERIFICAELEGIBILIDADE_QNAME);
    }

    public TissVerificaElegibilidade(WebServiceFeature... features) {
        super(__getWsdlLocation(), TISSVERIFICAELEGIBILIDADE_QNAME, features);
    }

    public TissVerificaElegibilidade(URL wsdlLocation) {
        super(wsdlLocation, TISSVERIFICAELEGIBILIDADE_QNAME);
    }

    public TissVerificaElegibilidade(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TISSVERIFICAELEGIBILIDADE_QNAME, features);
    }

    public TissVerificaElegibilidade(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TissVerificaElegibilidade(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TissVerificaElegibilidadePortType
     */
    @WebEndpoint(name = "tissVerificaElegibilidade_Port")
    public TissVerificaElegibilidadePortType getTissVerificaElegibilidadePort() {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tissverificaelegibilidade/v30301", "tissVerificaElegibilidade_Port"), TissVerificaElegibilidadePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TissVerificaElegibilidadePortType
     */
    @WebEndpoint(name = "tissVerificaElegibilidade_Port")
    public TissVerificaElegibilidadePortType getTissVerificaElegibilidadePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tissverificaelegibilidade/v30301", "tissVerificaElegibilidade_Port"), TissVerificaElegibilidadePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TISSVERIFICAELEGIBILIDADE_EXCEPTION!= null) {
            throw TISSVERIFICAELEGIBILIDADE_EXCEPTION;
        }
        return TISSVERIFICAELEGIBILIDADE_WSDL_LOCATION;
    }

}
